openapi: 3.0.0
info:
  title: Exemplo de API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Obtém a lista de usuários
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      summary: Obtém um usuário pelo ID
      parameters:
        - name: id
          in: path
          description: ID do usuário
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        nameFirst:
          type: string
