name: Kong Deck Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Print input_file.yaml
          run: cat ${{ github.workspace }}/openapi.yaml
  
        - name: Install openapi2jsonschema
          run: npm install @openapi-contrib/openapi-schema-to-json-schema
  
        - name: Convert OpenAPI to JSON Schema
          run: |
            npx openapi2jsonschema -i ${{ github.workspace }}/openapi.yaml -o ${{ github.workspace }}/output_directory
                    
        - name: Loop through files
          run: |
              for file in $(find "${{ github.workspace }}/output_directory" -type f); do
                echo "Processing file: $file"
                # Faça o que você precisa com cada arquivo aqui
              done
        
        - name: Download deck.yaml
          uses: actions/upload-artifact@v2
          with:
            name: deck
            path: ${{ github.workspace }}/deck.yaml
              
        - name: Install Kong Deck
          run: npm install -g kong-deck
  
        - name: Deploy Kong Configuration
          run: kong-deck sync --config ${{ github.workspace }}/deck.yaml
