name: Kong Deck POC

on:
  push:
    branches:
      - main
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prompt for approval
        id: approval
        run: echo "Do you want to proceed with this workflow? (y/n)"
      
      - name: Run workflow if approved
        if: ${{ steps.approval.outputs.result == 'y' }}
        run: |
          # Add your workflow steps here
          echo "Workflow execution begins!"
      