name: Kong Deck Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Print input_file.yaml
          run: cat ${{ github.workspace }}/openapi.yaml
  
        - name: Install openapi2jsonschema
          run: npm install @openapi-contrib/openapi-schema-to-json-schema
  
        - name: Convert OpenAPI to JSON Schema
          run: |
            npx openapi2jsonschema -i ${{ github.workspace }}/openapi.yaml -o ${{ github.workspace }}/output_directory
        
        - name: Check directory for files
          run: |
              file_count=$(ls -1A "${{ github.workspace }}/output_directory" | wc -l)
              if [ $file_count -gt 0 ]; then
                echo "Arquivos criados"
              else
                echo "Diretório está vazio"
                exit 1 # Encerrar a execução da pipeline com falha
              fi
            
        - name: Generate Kong Deck Configuration
          run: |
            # Aqui você pode adicionar o código necessário para gerar o arquivo deck.yaml com base nos esquemas JSON convertidos
  
        - name: Install Kong Deck
          run: npm install -g kong-deck
  
        - name: Deploy Kong Configuration
          run: kong-deck sync --config ${{ github.workspace }}/deck.yaml
